[package]
name = "iodisco-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
iodisco = { path = "..", features = ["full"] }
clap = { version = "4.0", features = ["derive", "env"] }
anyhow = "1.0"
