[package]
name = "gpuinfo-minimal"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gpuinfo"
path = "src/main.rs"

[dependencies]
iodisco = { path = "../iodisco", default-features = false, features = ["mali"] }
