[package]
name = "gpuinfo-minimal"
version = "0.1.0"
edition = "2021"
[[bin]]
name = "gpuinfo-minimal"
path = "src/main.rs"
default-features = false

[dependencies]
iodisco = { path = "..", default-features = false, features = ["mali"] }
